version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 100adaychallenge-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - sqlite_data:/var/www/html/database
    networks:
      - 100adaychallenge-network
    environment:
      - APP_NAME=100ADayChallenge
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=${APP_URL}
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=sqlite
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=database
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - MAIL_MAILER=smtp
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - AUTHORIZED_EMAIL=${AUTHORIZED_EMAIL}
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.service=100adaychallenge"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 100adaychallenge-worker
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work --verbose --no-interaction --sleep=1 --tries=3
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - sqlite_data:/var/www/html/database
    networks:
      - 100adaychallenge-network
    environment:
      - APP_NAME=100ADayChallenge
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=${APP_URL}
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=sqlite
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=database
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - MAIL_MAILER=smtp
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - AUTHORIZED_EMAIL=${AUTHORIZED_EMAIL}
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.service=worker"

volumes:
  sqlite_data:
    driver: local

networks:
  100adaychallenge-network:
    driver: bridge
